#
# Main configuration file
#

# / = = = = = = = = = = = = = = = = \
# |    SECURITYVILLAGER SETTINGS    |
# \ = = = = = = = = = = = = = = = = /
securityvillagers:
  updates:
    # Check for updates, recommended. SecurityVillagers will check for updates when the server finish to load
    check: true
    # Send a message to admins if an update is available
    warn: true

  logging:
    # Enable debug messages
    debug: false
    save-file:
      # Save to file log messages
      enable: false
      # Format of messages
      format: "%date% [%time%] %message%\n"
      # Log file name
      file: "log.txt"


# / = = = = = = = = = = = = = = = = \
# |        STORAGE  SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
storage:
  # The storage is used if you set protection type to CUSTOM
  # Name of the database file
  database-file: "database.yml"


# / = = = = = = = = = = = = = = = = \
# |        GENERAL  SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
general:
  # Choose how to protect mobs
  # => global    | Protect all
  # => custom    | Select mobs to protect and use /sv protect
  # => factions  | Protect mobs in your lands from other player attacks
  protection-type: global

  damage:
    # Just disable any type of damage to mobs
    immortal: false
    # Prevent player to attack
    disable-hit-damage: true
    # Prevent player to shoot
    disable-arrow-damage: true
    # Worlds where disable (for every world use '*')
    prevent-worlds:
      - '*'

  interact:
    # Prevent player to trade
    disable-trade: false
    # Prevent player to use egg
    disable-egg: true
    # Worlds where disable (for every world use '*')
    prevent-worlds:
      - '*'

  mute:
    # Mute villagers ambient sounds
    # > It requires ProtocolLib plugin <
    # Give permission "securityvillagers.admin.bypass.mute" to bypass it
    disable-sound: false
    prevent-worlds:
      - '*'

  target:
    # Prevent mobs to be targeted
    # Mobs won't be attacked
    # e.g. prevents zombie follow when their protection is enabled
    disable-target: true
    prevent-worlds:
      - '*'

  factions:
    # Supported plugins:
    # => Factions, HCfactions and SavageFactions
    members-bypass-protection: true
    members-bypass-interact: true



# / = = = = = = = = = = = = = = = = \
# |          MOBS SETTINGS          |
# \ = = = = = = = = = = = = = = = = /
mobs:
  villager:
    protect: true
    prevent-interact: false
    spawn:
      prevent: false
      prevent-worlds:
        - '*'

  wandering-trader:
    protect: true
    prevent-interact: false
    spawn:
      prevent: false
      prevent-worlds:
        - '*'

  trader-llama:
    protect: true
    prevent-interact: false
    spawn:
      prevent: false
      prevent-worlds:
        - '*'

  iron-golem:
    protect: false
    spawn:
      prevent: false
      prevent-worlds:
        - '*'

  illager:
    evoker:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    illusioner:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    pillager:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    ravager:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    vex:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    vindicator:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'
    witch:
      protect: false
      spawn:
        prevent: false
        prevent-worlds:
          - '*'


# / = = = = = = = = = = = = = = = = \
# |         DAMAGE SETTINGS         |
# \ = = = = = = = = = = = = = = = = /
damage:
  # List of prevented damages
  mobs:
    evoker: false
    illusioner: false
    pillager: false
    ravager: false
    skeleton: false
    vex: false
    vindicator: false
    witch: false
    wither: false
    zombie: false

  other:
    # Damage caused when an entity contacts a block such a Cactus
    contact: false
    # Damage caused when an entity is colliding with too many entities
    cramming: false
    # Damage caused by dragons
    dragon: false
    # Damage caused by running out of air while in water
    drowning: false
    # Damage caused by explosions
    explosion: false
    # Damage caused when an entity falls a distance greater than 3 blocks
    fall: false
    # Damage caused by being hit by a falling block
    falling-block: false
    # Damage caused by fire
    fire: false
    # Damage caused when an entity steps on magma
    hot-floor: false
    # Damage caused by direct exposure to lava
    lava: false
    # Damage caused by being struck by lightning
    # Does not work in 1.8+ (The villager will be turned into a Witch)
    lightning: false
    # Damage caused by being hit by a damage potion or spell
    magic: false
    # Damage caused due to ongoing poison effect
    poison: false
    # Damage caused by being put in a block
    suffocation: false
    # Damage caused in retaliation to another attack by the Thorns enchantment
    thorns: false
    # Damage caused by falling into the void
    void: false


# / = = = = = = = = = = = = = = = = \
# |       SELECTION SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
selection:
  # Item that must be used to select villagers
  item: BLAZE_ROD
  # Clear selection on player leave
  clear-on-quit: true


# / = = = = = = = = = = = = = = = = \
# |       PROFESSION SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
profession:
  # Change villager protection with the command /sv profession
  enable: true
  # Add a cooldown to the command (bypass with securityvillagers.admin.profession.cooldown.bypass)
  cooldown: 0
  # Profession names
  # If you wanna disable one of them, you have to leave it empty
  professions:
    armorer: "Armorer"
    butcher: "Butcher"
    cartographer: "Cartographer"
    cleric: "Cleric"
    farmer: "Farmer"
    fisherman: "Fisherman"
    fletcher: "Fletcher"
    leatherworker: "Leatherworker"
    librarian: "Librarian"
    mason: "Mason"
    nitwit: "Nitwit"
    none: "None"
    shepherd: "Shepherd"
    toolsmith: "Toolsmith"
    weaponsmith: "Weaponsmith"


# / = = = = = = = = = = = = = = = = \
# |       CHANGE AGE SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
changeage:
  # Convert a villager from baby to adult, or vice versa
  # You have to select a villager then perform /sv changeage
  enable: true
  # Add a cooldown to the command (bypass with securityvillagers.admin.changeage.cooldown.bypass)
  cooldown: 0


# / = = = = = = = = = = = = = = = = \
# |         RENAME SETTINGS         |
# \ = = = = = = = = = = = = = = = = /
rename:
  # Enable villagers name editing with the command /sv rename
  # It requires selection system enabled
  enable: true


# / = = = = = = = = = = = = = = = = \
# |        COMMANDS SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
commands:
  # Enable tab support (/oa <tab> to see every allowed command)
  tab-support: true
  sv-description: "SecurityVillagers help page"
  main-commands:
    help: "help"
    sv: "sv"
    changeage: "changeage"
    profession: "profession"
    protect: "protect"
    reload: "reload"
    rename: "rename"
    version: "version"
  sub-commands:
    word-on: "on"
    word-off: "off"
    # Sub-command used to remove something
    remove: "remove"


dont-edit-this:
  version: 2