# 
# SecurityVillagers configuration file
#
# For a better configuration:
# - Use Notepad++
#   - View -> Symbols -> Show White Space and TAB (Active)
#   - Don't use arrows (tabs), but spaces
# - Set format (syntax) editor to YAML
#

# / = = = = = = = = = = = = = = = = \
# |   SECURITYVILLAGERS  SETTINGS   |
# \ = = = = = = = = = = = = = = = = /
securityvillagers:
  updates:
    # Check for updates, recommended. SecurityVillagers will check for updates when the server finish to load
    check: true
    # Send a message to admins if an update is available
    warn: true
  selection:
    # Enable selection system, you can select a villager to edit it
    enable: true
    # Choose the item to select villagers
    item: BLAZE_ROD

# / = = = = = = = = = = = = = = = = \
# |  SECURITYVILLAGERS PREVENTIONS  |
# \ = = = = = = = = = = = = = = = = /
preventions:
  # Prevent villagers to spawn
  spawn: false
  # Prevent villagers to be target (for example: from zombies if zombie protection enabled)
  target: true
  # Mute villager ambient sound (Damage/trades/etc.. enabled)
  # REQUIRES ProtocolLib PLUGIN
  # Give permission "securityvillagers.admin.bypass-mute" to bypass it
  mute-villager-sounds: false
  # Choose villagers to protect
  # global: protect ALL villagers
  # custom: select villagers to protect then /sv protect
  protection-type: global

# / = = = = = = = = = = = = = = = = \
# |        GENERAL  SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
general:
  damage:
    # Prevent basic attack damage from a player
    disable-hit-damage: true
    # Prevent arrow shooting damage from a player
    disable-arrow-damage: true
    # Prevent damages in these worlds (For every world use '*')
    prevent-worlds:
    - '*'
  interact:
    # Disable tradings
    disable-trade: false
    # Disable egg use on villagers
    disable-egg: true
    # Disable interact preventions n these worlds (For every world use '*')
    prevent-worlds:
    - '*'

# / = = = = = = = = = = = = = = = = \
# |        FACTIONS SETTINGS        |
# \ = = = = = = = = = = = = = = = = /
factions:
  # Enable Factions support
  # Supported: Factions, HCfactions, SavageFactions, FactionsOne
  # Bypass with permission 'securityvillagers.admin.bypass' (Potions still works)
  enable: false
  prevent-hit: true
  prevent-interact: true

# / = = = = = = = = = = = = = = = = \
# |         DAMAGE SETTINGS         |
# \ = = = = = = = = = = = = = = = = /
damage:
  # Prevent these damages
  mobs:
    skeleton: false
    wither: false
    zombie: false
  other:
    # Contact Damage = Damage on contact with an entity, cactus
    contact: false
    dragon: false
    drowning: false
    explosion: false
    fall: false
    falling-block: false
    fire: false
    hot-floor: false
    lava: false
    # Doesn't work in 1.8+ (The villager will be turned into Witch)
    lightning: false
    # Magic Damage = Damage Potion or Spells
    magic: false
    # Melting Damage = Damage on contact with fired entity
    melting: false
    poison: false
    suffocation: false
    thorns: false
    void: false

# / = = = = = = = = = = = = = = = = \
# |       IRON GOLEM SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
iron-golem:
  # Protect iron golems
  protect: false
  # Prevent spawn of iron golems
  prevent-spawn: false

# / = = = = = = = = = = = = = = = = \
# |       PROFESSION SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
profession:
  # Change profession's villager with a command
  enable: true
  # Rename commands
  professions:
    blacksmith: "Blacksmith"
    butcher: "Butcher"
    farmer: "Farmer"
    librarian: "Librarian"
    nitwit: "Nitwit"
    priest: "Priest"

# / = = = = = = = = = = = = = = = = \
# |       CHANGE AGE SETTINGS       |
# \ = = = = = = = = = = = = = = = = /
changeage:
  # Convert a villager from baby to adult, or viceversa
  # REQUIRES selection enabled
  enable: true
  item:
    # Use an item to convert the villager
    enable: false
    item: COMPASS
  # In which worlds enable the converter (For all worlds use '*')
  allowed-worlds:
  - '*'

# / = = = = = = = = = = = = = = = = \
# |         RENAME SETTINGS         |
# \ = = = = = = = = = = = = = = = = /
rename:
  # You can edit the name of a villager
  # REQUIRES selection enabled
  enable: true

dont-edit-this:
  config-version: 9