name: SecurityVillagers
author: AlessioDP
website: https://alessiodp.com/
main: com.alessiodp.securityvillagers.SecurityVillagers
version: ${project.version}
description: Customize your villagers protection
softdepend: [Factions, ProtocolLib]
commands:
  securityvillagers:
    aliases: sv
    description: Main command of SecurityVillagers
permissions:
  securityvillagers.egg:
    description: Allow use of eggs on villagers
  securityvillagers.hit:
    description: Allow melee attacks on villagers
  securityvillagers.shoot:
    description: Allow ranged attacks on villagers
  securityvillagers.trade:
    description: Allow trade with villagers
  securityvillagers.admin.bypass.factions:
    description: Bypass Factions preventions
  securityvillagers.admin.bypass.mute:
    description: Bypass villagers mute
  securityvillagers.admin.changeage:
    description: Allow access to /sv changeage
  securityvillagers.admin.help:
    description: Allow access to /sv help
  securityvillagers.admin.profession:
    description: Allow access to /sv profession
  securityvillagers.admin.reload:
    description: Allow access to /sv reload
  securityvillagers.admin.selection:
    description: Allow use of an item to select villagers
  securityvillagers.admin.updates:
    description: Send a message if there is an update
  securityvillagers.allow.*:
    default: op
    description: Can attack and interact with villagers
    children:
      securityvillagers.hit: true
      securityvillagers.shoot: true
      securityvillagers.trade: true
      securityvillagers.egg: true
      securityvillagers.admin.bypass.factions: true
  securityvillagers.admin.*:
    default: op
    description: All permissions are granted
    children:
      securityvillagers.allow.*: true
      securityvillagers.admin.bypass.mute: true
      securityvillagers.admin.changeage: true
      securityvillagers.admin.help: true
      securityvillagers.admin.profession: true
      securityvillagers.admin.reload: true
      securityvillagers.admin.selection: true
      securityvillagers.admin.updates: true